#!/usr/bin/env python

import sys
import unittest
import argparse
from contextlib import contextmanager

from tests import conf

TESTS_DIR = "tests"


def parse_args():
    parser = argparse.ArgumentParser(
        description="runs specified tests, "
                    "or run all discovered tests if no are tests specified")

    parser.add_argument("tests", metavar="test", nargs='*',
                        help="test case to run")

    parser.add_argument("--coverage", action="store_true", default=False)

    return parser.parse_args()


def get_testsuite(tests):
    test_loader = unittest.TestLoader()
    if len(tests) == 0:
        # no test names specified, run all discovered tests
        return test_loader.discover(TESTS_DIR)

    test_names = ["%s.%s" % (TESTS_DIR, name) for name in tests]
    return test_loader.loadTestsFromNames(test_names)


@contextmanager
def coverage(enabled):
    conf.WITH_COVERAGE = enabled

    if enabled:
        # only import coverage if we actually using
        from coverage import Coverage
        cov = Coverage(config_file=True, auto_data=True, data_suffix=True)
        cov.start()

        yield None

        cov.stop()
        cov.save()
    else:
        yield None


args = parse_args()

test_suites = get_testsuite(args.tests)

with coverage(args.coverage):
    res = unittest.TextTestRunner(verbosity=2).run(test_suites)
    if not res.wasSuccessful():
        sys.exit(1)
